name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      APP_URL: "https://demoqa.com/"
      USER_NAME: aframe
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
     
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
            python-version: 3.8

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
    
      - name: Install dependencies
        run: |
          pipenv install --dev  # Install dependencies from Pipfile.lock
   
      - name: Run tests in Chrome
        env:
          BROWSER: chrome
        run: |
          pipenv run behavex -D browser="$BROWSER" -D headless_browser=true --define APP_URL="${APP_URL}" --define USERNAME="${USER_NAME}" --define PASSWORD="${PASSWORD}"

      - name: Deploy report to GitHub Pages
        if: always()
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.email "creusserp@gmail.com"
          git config --global user.name "creusserp"
          git clone https://x-access-token:${GH_PAT}@github.com/creusserp/apu-frame.git gh-pages
          cd gh-pages
          git checkout gh-pages || git checkout --orphan gh-pages
          cp ../output/report.html report.html
          git add report.html
          git commit -m "Update test report"
          git push origin gh-pages
      
      - name: Store Behave Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: behave-results
          path: output/behave

      - name: Store All Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: all-artifacts
          path: output
          
          
    